sudo: required

language: ruby

env:
 - TEST_THAT_FILTER=_unit_
 - TEST_THAT_FILTER=900_integration_
 - TEST_THAT_FILTER=910_integration_
 - TEST_THAT_FILTER=920_integration_
 - TEST_THAT_FILTER=990_integration_


services:
 - docker

before_install:
 - docker build -t sagebionetworks/mpower-processing .

script:
 # Now run the tests.
 - docker run -w /mPowerProcessing/tests -e SYNAPSE_USERNAME=$SYNAPSE_USERNAME -e SYNAPSE_APIKEY=$SYNAPSE_APIKEY -e BRIDGE_USERNAME=$BRIDGE_USERNAME -e BRIDGE_PASSWORD=$BRIDGE_PASSWORD -e TEST_THAT_FILTER=$TEST_THAT_FILTER sagebionetworks/mpower-processing bash -c "R --no-save < /mPowerProcessing/tests/testthat.R"
 
after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - test $TRAVIS_PULL_REQUEST == "false" && docker push sagebionetworks/mpower-processing
 # Delete the cached registry credentials
 - test $TRAVIS_PULL_REQUEST == "false" && rm /home/travis/.docker/config.json
 